ex10_html-css-fundamentals-part2
NBergal/external-courses pull request #8
Opened 2020-04-03 21:31 UTC by NBergal

2020-04-10 16:08 UTC, dfolomkin requested changes

2020-04-10 16:08 UTC, dfolomkin commented on src/ex10_html-css-fundamentals-part2/task-04.html
> +            <div class="container">
здесь можно было бы использовать <section> и <article>

2020-04-10 16:08 UTC, dfolomkin commented on src/ex4_js-objects-part2/README.md
> +Написать функцию, которая ищет одну строку в другой строке и возвращает `true`, если такая строка найдена. Иначе - `false`
лучше всего не смешивать ченжи от разных заданий в одном ПР (но скорее всего это просто ошибка)

2020-04-10 16:11 UTC, NBergal commented on src/ex4_js-objects-part2/README.md
> +Написать функцию, которая ищет одну строку в другой строке и возвращает `true`, если такая строка найдена. Иначе - `false`
мне это исправить, если это не моя ошибка?

2020-04-10 16:12 UTC, NBergal commented on src/ex10_html-css-fundamentals-part2/task-04.html
> +            <div class="container">
Что здесь можно было бы использовать? не понял, объясните

2020-04-12 16:36 UTC, aneelia commented on src/ex10_html-css-fundamentals-part2/task-04.html
> +            <div class="container">
Дим, когда пишешь какой то код заключай его в обратные кавычки, потому что гитхаб проглатывает теги или джс. Уточни пожалуйста что ты тут имел ввиду. ` кавычки вот такие \` `

2020-04-12 16:37 UTC, aneelia commented on src/ex4_js-objects-part2/README.md
> +Написать функцию, которая ищет одну строку в другой строке и возвращает `true`, если такая строка найдена. Иначе - `false`
ваще лучше бы проребейзить по мастеру, но оставь

2020-05-03 13:53 UTC, merged